name: oidc_linux
description: Linux implementation of the oidc plugin
version: 0.3.0+12
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_linux
homepage: https://bdaya-dev.github.io/oidc/
publish_to: none
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      linux:
        pluginClass: OidcPlugin
        dartPluginClass: OidcLinux

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core:
    path: ../oidc_core
  
  oidc_desktop:
    path: ../oidc_desktop
  oidc_platform_interface:
    path: ../oidc_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <8.0.0"
