name: oidc_android
description: Android implementation of the oidc plugin
version: 0.6.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_android
homepage: https://bdaya-dev.github.io/oidc/

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      android:
        package: com.bdayadev.oidc
        pluginClass: OidcPlugin
        dartPluginClass: OidcAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  oidc_core:
    path: ../oidc_core

  oidc_flutter_appauth:
    path: ../oidc_flutter_appauth
  oidc_platform_interface:
    path: ../oidc_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ">=5.0.0 <8.0.0"
