name: oidc_web
description: Web implementation of the oidc plugin
version: 0.6.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_web
homepage: https://bdaya-dev.github.io/oidc/
publish_to: none
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      web:
        pluginClass: OidcWeb
        fileName: oidc_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  oidc_core:
    path: ../oidc_core

  oidc_platform_interface:
    path: ../oidc_platform_interface
  oidc_web_core: 
    path: ../oidc_web_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <8.0.0"
